"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$python\
$git_branch\
$git_state\
$git_status\
$character"""

[directory]
style = "blue"

[python]
format = '[($virtualenv )]($style)'
style = "yellow"

[git_branch]
format = "[$branch ]($style)"
style = "bright-black"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[git_status]
format = "[($ahead_behind )]($style)"
style = "cyan"
ahead = "${count}⇡"
behind = "${count}⇣"
diverged = "${behind_count}⇣${ahead_count}⇡"

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"
